services:
  flaghunter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flaghunter_with_kali_mcp
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - FLAGHUNTER_MODEL=${FLAGHUNTER_MODEL}
      - FLAGHUNTER_DEBUG=${FLAGHUNTER_DEBUG:-false}
    
    networks:
      - flaghunter-net
    stdin_open: true
    tty: true


networks:
  flaghunter-net:
    driver: bridge
