"""Canonical registration of every active schema in the system.

This is the **single place** that knows about all the schemas the rest
of the codebase reads or writes. It is invoked once at startup (or on
demand from tests) to populate an in-memory
:class:`flaghunter.domain.schema_catalog.InMemorySchemaRegistry` and
nothing else.

Scope (per §13.4 C-01 and §10.3 of the optimization guide):

* Every ACTIVE schema is registered with an explicit owner module.
* Each schema carries a reader/writer compatibility list so that
  ``is_compatible()`` answers can drive a future migration matrix.
* The list is deliberately a **seed**, not the whole truth. New
  schemas must be added here as they are introduced; new owners must
  appear here before they ship.

What is *not* in this file (yet):

* The 600+ ``version=...`` parameters that pepper the codebase. Those
  are application-level option versions, not data schemas; cataloging
  them is out of scope for C-01.
* The ``p2/p3/p4`` working names. Per the masterplan these are
  historical migration sources only and must not appear in the
  canonical registry.

Each registered schema is a ``SchemaRecord`` from
:mod:`flaghunter.domain.schema_catalog`; see that module for the
canonical field list and validation rules.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from .schema_catalog import InMemorySchemaRegistry, SchemaRecord, SchemaStatus

if TYPE_CHECKING:
    pass


# --- Domain schemas (already versioned) ---------------------------------
# These three existed before the registry; C-01 just makes them
# discoverable from one place.

_TASK_CANCELLATION_V1 = SchemaRecord(
    schema_id="task.cancellation",
    version="v1",
    owner="flaghunter.domain.cancellation",
    status=SchemaStatus.ACTIVE,
    description=(
        "Cancellation token + scope + registry primitives that all "
        "production control surfaces (A-02) consume. Version 1 covers "
        "the current blocking + async interrupt + parent-propagation "
        "semantics; bump to v2 only if a non-additive shape change is "
        "needed."
    ),
    storage_location="in-process (CancellationRegistry singleton)",
    introduced_at="2026-07-31",
    reader_compat=("task.cancellation@v1",),
    writer_compat=("task.cancellation@v1",),
)


_TASK_LIFECYCLE_V1 = SchemaRecord(
    schema_id="task.lifecycle",
    version="v1",
    owner="flaghunter.domain.task_lifecycle",
    status=SchemaStatus.ACTIVE,
    description=(
        "Canonical task state machine (TaskState + Dialect + transition "
        "service). Production control surfaces (web, MCP, dispatcher) "
        "must consume this single source via the dialect mappers; any "
        "ad-hoc status vocabulary in a control surface is a regression."
    ),
    storage_location="in-process (TaskState enum + transition service)",
    introduced_at="2026-07-31",
    reader_compat=("task.lifecycle@v1",),
    writer_compat=("task.lifecycle@v1",),
)


_QUALITY_MANIFEST_V1 = SchemaRecord(
    schema_id="quality.manifest",
    version="v1",
    owner="flaghunter.quality.acceptance",
    status=SchemaStatus.ACTIVE,
    description=(
        "Schema-versioned quality manifest consumed by the acceptance "
        "runner. Generated by scripts/build_quality_gates.py from a "
        "single Python source of truth. Bump on any non-additive change "
        "to gate / acceptance / evidence / report shape."
    ),
    storage_location="quality-gates.json (repo root)",
    introduced_at="2026-08-03",
    reader_compat=("quality.manifest@v1",),
    writer_compat=("quality.manifest@v1",),
)


# --- Port contracts -----------------------------------------------------
# Each port is its own schema — its method signatures are the contract.
# The adapter that satisfies a port is responsible for picking the
# concrete on-disk / on-wire shape; the registry only records the
# contract boundary.

_PORT_SCHEMAS: tuple[SchemaRecord, ...] = (
    SchemaRecord(
        schema_id="port.tool_runner",
        version="v1",
        owner="flaghunter.ports.tool_runner",
        status=SchemaStatus.ACTIVE,
        description=(
            "ToolRunnerPort: the boundary every tool execution must "
            "cross. Wraps the executor + scanner + provenance so "
            "consumers depend on the port, not the adapter."
        ),
        storage_location="in-process (Protocol structural type)",
        introduced_at="2026-07-04",
        reader_compat=("port.tool_runner@v1",),
        writer_compat=("port.tool_runner@v1",),
    ),
    SchemaRecord(
        schema_id="port.runtime_action",
        version="v1",
        owner="flaghunter.ports.runtime_action",
        status=SchemaStatus.ACTIVE,
        description=(
            "RuntimeActionPort: the boundary for out-of-process "
            "commands (subprocess / docker exec / ssh). Adapters are "
            "swappable per runtime profile."
        ),
        storage_location="in-process (Protocol structural type)",
        introduced_at="2026-07-04",
        reader_compat=("port.runtime_action@v1",),
        writer_compat=("port.runtime_action@v1",),
    ),
    SchemaRecord(
        schema_id="port.proof_authority",
        version="v1",
        owner="flaghunter.ports.proof_authority",
        status=SchemaStatus.ACTIVE,
        description=(
            "VerifierPort + ProofAuthorityPort: the proof boundary. "
            "Only verifier output can upgrade a candidate claim to "
            "proof; no other component is allowed to write proof."
        ),
        storage_location="in-process (Protocol structural type)",
        introduced_at="2026-07-04",
        reader_compat=("port.proof_authority@v1",),
        writer_compat=("port.proof_authority@v1",),
    ),
    SchemaRecord(
        schema_id="port.state_store",
        version="v1",
        owner="flaghunter.ports.state_store",
        status=SchemaStatus.ACTIVE,
        description=(
            "StateStorePort + ClaimStorePort: the durable state and "
            "claim boundary. The claim store is the canonical owner "
            "of candidate / verified / rejected claim state."
        ),
        storage_location="in-process (Protocol structural type)",
        introduced_at="2026-07-04",
        reader_compat=("port.state_store@v1",),
        writer_compat=("port.state_store@v1",),
    ),
    SchemaRecord(
        schema_id="port.audit_store",
        version="v1",
        owner="flaghunter.ports.audit_store",
        status=SchemaStatus.ACTIVE,
        description=(
            "AuditStorePort + ArtifactStorePort + CheckpointStorePort "
            "+ ReadModelStorePort: the append/lookup boundary for "
            "audit events, immutable artifacts, checkpoints, and "
            "materialised read models."
        ),
        storage_location="in-process (Protocol structural type)",
        introduced_at="2026-07-04",
        reader_compat=("port.audit_store@v1",),
        writer_compat=("port.audit_store@v1",),
    ),
    SchemaRecord(
        schema_id="port.crew_bridge",
        version="v1",
        owner="flaghunter.ports.crew_bridge",
        status=SchemaStatus.ACTIVE,
        description=(
            "CrewBridgePort + TaskDAGRunnerPort: the multi-agent "
            "boundary. The single-agent dispatcher must not call into "
            "crew orchestration directly."
        ),
        storage_location="in-process (Protocol structural type)",
        introduced_at="2026-07-04",
        reader_compat=("port.crew_bridge@v1",),
        writer_compat=("port.crew_bridge@v1",),
    ),
    SchemaRecord(
        schema_id="port.process_lock",
        version="v1",
        owner="flaghunter.ports.process_lock",
        status=SchemaStatus.ACTIVE,
        description=(
            "ProcessLockPort: cross-process advisory exclusive "
            + "lock on a path. Closes the C-03 gap that AtomicFilePort "
            + "(C-02) does not cover: per-process atomic writes are "
            + "safe, but two processes writing the same JSON snapshot "
            + "at the same time still race. Backed by fcntl.flock on "
            + "POSIX and msvcrt.locking on Windows over a <target>.lock "
            + "sidecar. JSON snapshot writers MUST acquire this lock "
            + "across their read-modify-replace cycle; NDJSON append "
            + "writers do NOT need it (POSIX O_APPEND is per-line "
            + "atomic). The lock is advisory; misuse is a code review "
            + "concern, not a runtime enforcement. See ADR 0001."
        ),
        storage_location="in-process (Protocol structural type)",
        introduced_at="2026-08-04",
        reader_compat=("port.process_lock@v1",),
        writer_compat=("port.process_lock@v1",),
    ),
    SchemaRecord(
        schema_id="port.identity_service",
        version="v1",
        owner="flaghunter.ports.identity_service",
        status=SchemaStatus.ACTIVE,
        description=(
            "IdentityServicePort: single source of identity. Every new id is a full 32-hex uuid4 (no truncation) with an optional display prefix; the prefix is display only, the canonical id is the hex suffix. See ADR 0002."
        ),
        storage_location="in-process (Protocol structural type)",
        introduced_at="2026-08-04",
        reader_compat=("port.identity_service@v1",),
        writer_compat=("port.identity_service@v1",),
    ),
    SchemaRecord(
        schema_id="port.time_service",
        version="v1",
        owner="flaghunter.ports.time_service",
        status=SchemaStatus.ACTIVE,
        description=(
            "TimeServicePort: single source of timestamps. utc_now() is always aware UTC; utc_now_iso() is the canonical ...Z wire form; monotonic_now() is for durations (never subtract from a wall clock). See ADR 0002."
        ),
        storage_location="in-process (Protocol structural type)",
        introduced_at="2026-08-04",
        reader_compat=("port.time_service@v1",),
        writer_compat=("port.time_service@v1",),
    ),
    SchemaRecord(
        schema_id="port.atomic_file",
        version="v1",
        owner="flaghunter.ports.atomic_file",
        status=SchemaStatus.ACTIVE,
        description=(
            "AtomicFilePort: low-level atomic text-file read/write "
            + "primitive. Every higher-level state store (state, "
            + "conversation, checkpoint, harness ledger) MUST use this "
            + "port instead of bare Path.write_text to avoid producing "
            + "half-written files on crash, signal, or power loss. The "
            + "filesystem implementation writes to a uniquely-named temp "
            + "file in the same directory as the target, fsyncs it, then "
            + "os.replaces onto the target. Future adapters (S3, "
            + "object-store write-then-rename) plug in at the same "
            + "boundary without changing callers."
        ),
        storage_location="in-process (Protocol structural type)",
        introduced_at="2026-08-04",
        reader_compat=("port.atomic_file@v1",),
        writer_compat=("port.atomic_file@v1",),
    ),
    SchemaRecord(
        schema_id="port.task_ingress",
        version="v1",
        owner="flaghunter.ports.task_ingress",
        status=SchemaStatus.ACTIVE,
        description=(
            "TaskIngressPort: the boundary every external task entry "
            "point (web, MCP, CLI, TUI) must cross. New entry points "
            "ship adapters; the domain sees the port only."
        ),
        storage_location="in-process (Protocol structural type)",
        introduced_at="2026-07-04",
        reader_compat=("port.task_ingress@v1",),
        writer_compat=("port.task_ingress@v1",),
    ),
)


# --- Public entry point -------------------------------------------------


def register_all_active_schemas(
    registry: InMemorySchemaRegistry,
) -> InMemorySchemaRegistry:
    """Populate ``registry`` with every ACTIVE schema the system knows
    about and return the same instance for chaining.

    The function is idempotent: calling it twice on the same registry
    is safe. It is also the *only* sanctioned way to add an active
    schema; new owners must extend this list (or its successor) so
    that ``active_schemas()`` stays an authoritative answer to the
    C-01 acceptance target.
    """
    for record in (
        _TASK_CANCELLATION_V1,
        _TASK_LIFECYCLE_V1,
        _QUALITY_MANIFEST_V1,
        *_PORT_SCHEMAS,
    ):
        registry.register(record.to_mapping())
    return registry


def known_active_schema_count() -> int:
    """Return how many ACTIVE schemas the canonical catalog contains
    without actually building a registry — useful for tests and for
    the C-01 acceptance guard.
    """
    return 3 + len(_PORT_SCHEMAS)
